import unittest
from main import *

class UnitTests(unittest.TestCase) :
    def test_histogram(self) : 
        fighand=plt.gca()
        figdat = fighand.get_lines()[0].get_xydata()
        this_x, this_y = zip(*figdat)
        dx = this_x[1] - this_x[0]
        for i in range(len(this_x)) :
            l, u = this_x[i] - 0.5*dx, this_x[i] + 0.5*dx
            p = scipy.stats.f.cdf(u,4,45) - scipy.stats.f.cdf(l,4,45)
            var = p*(1-p)
            confl = scipy.stats.norm.ppf(0.01,loc=0,scale=np.sqrt(var))
            confu = scipy.stats.norm.ppf(0.99,loc=0,scale=np.sqrt(var))
            self.assertTrue( this_y[i]*dx > confl and this_y[i]*dx < confu, "The histogram you have generated is not correct.  I test your code by doing a hypothesis test at the 1% significance level.  The null and alternative hypothesis in this test are that the value generated by your function is a sample from the distribution of interest and that it is not.  Obviously, there is thus a small probability that a correct code will not pass this test.")
            
    def test_normalisation(self) :
        fighand=plt.gca()
        figdat = fighand.get_lines()[0].get_xydata()
        this_x, this_y = zip(*figdat)
        self.assertTrue( np.abs( sum(this_y)*(this_x[1]-this_x[0]) - 1 )<1e-7, "Your histogram is not normalised correctly" )
        
    def test_f_generation(self) : 
        for i in range(2,5) :
            for j in range(10,15) :
                t = gen_f_variable( i, j )
                pval = scipy.stats.f.cdf( t, i-1, i*j-i )
                self.assertTrue( pval<0.99, "Your gen_f_variable function is not working correctly.  I test your code by doing a hypothesis test at the 1% significance level.  The null and alternative hypothesis in this test are that the value generated by your function is a sample from the distribution of interest and that it is not.  Obviously, there is thus a small probability that a correct code will not pass this test" )
